### ISSUE TITLE
Suggestion The source can be videos and not webcams

### ISSUE THREAD

**Issue by joaopalma5** [gen2brain/cam2ip#3]
Can put a option to display videos like webcam?

**Comment by gen2brain** [comment]
It is doable, with VideoCapture instead of CameraCapture.
 OpenCV will need to be compiled with ffmpeg support, so that will complicate static release builds a little. 

I will try something when I find time, I played with some ffmpeg wrapper to do similar thing, with OpenCV it should be much easier. Just not sure if it fits for current name of the project ;)

**Comment by gen2brain** [comment]
Added in https://github.com/gen2brain/cam2ip/commit/173deebc8866407b4e28049b8658adb5ac4cd0b8 .
