### ISSUE TITLE
Timestamp Scaling?

### ISSUE THREAD

**Issue by incith** [gen2brain/cam2ip#47]
Could we get a simple option to perhaps scale the timestamp size?  It's verrrry tiny on my 1080 stream!

Otherwise, this is great.

**Comment by gen2brain** [comment]
Sorry, currently it uses https://github.com/pbnjay/pixfont, which is a simple lightweight pixmap font without support for scaling (8x8 pixel fixed width). In order to add an option for scaling something like freetype is needed, probably with TrueType runtime font dependency etc. That will complicate and add complexity to simple tasks, not sure I want to do that.

**Comment by incith** [comment]
Understood, thank you
